TYPO3:
  Flow:
    security:
      enable: TRUE
      firewall:
        rejectAll: FALSE
        filters:
          -
            patternType:  'URI'
            patternValue: '/.*/.*/.*'
            interceptor:  'AccessGrant'
      authentication:
        authenticationStrategy: oneToken
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider