TYPO3:
  Flow:
    error:
      exceptionHandler:
        className: 'Intega3\Core\Error\ExceptionHandler'

    security:
      enable: TRUE
      firewall:
        rejectAll: FALSE
        filters:
          -
            patternType:  'URI'
            patternValue: '/.*/.*/.*'
            interceptor:  'AccessGrant'
      authentication:
        authenticationStrategy: oneToken
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: 'WebRedirect'
            entryPointOptions:
              routeValues:
                '@package': 'Intega3.Core'
                '@controller': 'Login'
                '@action': 'index'